import { Project, Bounty } from "./types";

// Mock Projects Data
export const mockProjects: Project[] = [
  {
    id: "proj-1",
    title: "Stellar DeFi Dashboard",
    description:
      "A comprehensive dashboard for tracking DeFi protocols on Stellar network. Features real-time analytics, portfolio tracking, and yield optimization.",
    tags: ["DeFi", "Frontend", "Analytics", "Stellar"],
    status: "active",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-20"),
    creator: "stellar_dev",
    category: "DeFi",
    milestones: 5,
    completedMilestones: 3,
  },
  {
    id: "proj-2",
    title: "NFT Marketplace on Stellar",
    description:
      "Decentralized NFT marketplace built on Stellar. Supports minting, trading, and royalty management with low transaction fees.",
    tags: ["NFT", "Smart Contracts", "Full Stack", "Stellar"],
    status: "active",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-22"),
    creator: "nft_builder",
    category: "NFT",
    milestones: 8,
    completedMilestones: 5,
  },
  {
    id: "proj-3",
    title: "Cross-Chain Bridge Protocol",
    description:
      "Secure bridge protocol enabling asset transfers between Stellar and other major blockchains.",
    tags: ["DeFi", "Smart Contracts", "Security", "Infrastructure"],
    status: "active",
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-18"),
    creator: "bridge_team",
    category: "Infrastructure",
    milestones: 6,
    completedMilestones: 2,
  },
  {
    id: "proj-4",
    title: "Stellar Mobile Wallet",
    description:
      "User-friendly mobile wallet for Stellar assets with built-in DEX integration and staking features.",
    tags: ["Mobile", "Frontend", "Web3", "Stellar"],
    status: "active",
    createdAt: new Date("2023-12-20"),
    updatedAt: new Date("2024-01-21"),
    creator: "mobile_dev",
    category: "Wallet",
    milestones: 10,
    completedMilestones: 8,
  },
  {
    id: "proj-5",
    title: "DAO Governance Platform",
    description:
      "Decentralized governance platform for DAOs on Stellar with voting mechanisms and proposal management.",
    tags: ["Smart Contracts", "Frontend", "Backend", "Web3"],
    status: "completed",
    createdAt: new Date("2023-11-01"),
    updatedAt: new Date("2023-12-15"),
    creator: "dao_builders",
    category: "Governance",
    milestones: 4,
    completedMilestones: 4,
  },
  {
    id: "proj-6",
    title: "Stellar Analytics Engine",
    description:
      "Advanced analytics engine for Stellar blockchain data with customizable dashboards and alerts.",
    tags: ["Analytics", "Backend", "Infrastructure", "Stellar"],
    status: "active",
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-19"),
    creator: "analytics_pro",
    category: "Analytics",
    milestones: 7,
    completedMilestones: 4,
  },
  {
    id: "proj-7",
    title: "Smart Contract Testing Suite",
    description:
      "Comprehensive testing framework for Stellar smart contracts with automated security audits.",
    tags: ["Testing", "Security", "Smart Contracts", "Infrastructure"],
    status: "paused",
    createdAt: new Date("2023-12-01"),
    updatedAt: new Date("2024-01-10"),
    creator: "test_master",
    category: "Development Tools",
    milestones: 5,
    completedMilestones: 2,
  },
  {
    id: "proj-8",
    title: "Decentralized Identity System",
    description:
      "Self-sovereign identity solution on Stellar for secure credential management and verification.",
    tags: ["Security", "Smart Contracts", "Backend", "Web3"],
    status: "active",
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-22"),
    creator: "identity_dev",
    category: "Identity",
    milestones: 6,
    completedMilestones: 3,
  },
  {
    id: "proj-9",
    title: "Stellar Documentation Hub",
    description:
      "Comprehensive documentation platform with interactive tutorials and code examples for Stellar developers.",
    tags: ["Documentation", "Frontend", "Design"],
    status: "completed",
    createdAt: new Date("2023-10-15"),
    updatedAt: new Date("2023-12-01"),
    creator: "docs_team",
    category: "Education",
    milestones: 3,
    completedMilestones: 3,
  },
  {
    id: "proj-10",
    title: "Yield Aggregator Protocol",
    description:
      "Automated yield optimization protocol that finds the best returns across Stellar DeFi platforms.",
    tags: ["DeFi", "Smart Contracts", "Backend", "Analytics"],
    status: "active",
    createdAt: new Date("2024-01-14"),
    updatedAt: new Date("2024-01-21"),
    creator: "yield_hunter",
    category: "DeFi",
    milestones: 8,
    completedMilestones: 4,
  },
];

// Mock Bounties Data
export const mockBounties: Bounty[] = [
  {
    id: "bounty-1",
    title: "Implement Multi-Signature Wallet Feature",
    description:
      "Add multi-signature functionality to existing Stellar wallet with customizable approval thresholds.",
    tags: ["Smart Contracts", "Security", "Backend"],
    reward: 5000,
    currency: "USDC",
    claimingModel: "application",
    status: "open",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    creator: "wallet_project",
    difficulty: "advanced",
    deadline: new Date("2024-02-20"),
  },
  {
    id: "bounty-2",
    title: "Design Landing Page for DeFi Protocol",
    description:
      "Create modern, responsive landing page design with dark mode support and animated elements.",
    tags: ["Design", "Frontend"],
    reward: 2000,
    currency: "USDC",
    claimingModel: "competition",
    status: "open",
    createdAt: new Date("2024-01-19"),
    updatedAt: new Date("2024-01-21"),
    creator: "defi_startup",
    difficulty: "intermediate",
    deadline: new Date("2024-02-10"),
  },
  {
    id: "bounty-3",
    title: "Fix Security Vulnerability in Smart Contract",
    description:
      "Identify and fix critical security vulnerability in liquidity pool smart contract.",
    tags: ["Security", "Smart Contracts", "Testing"],
    reward: 8000,
    currency: "USDC",
    claimingModel: "single-claim",
    status: "in-progress",
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-22"),
    creator: "security_team",
    difficulty: "advanced",
    deadline: new Date("2024-02-05"),
  },
  {
    id: "bounty-4",
    title: "Build Mobile App UI Components",
    description:
      "Create reusable React Native components for Stellar wallet mobile app.",
    tags: ["Mobile", "Frontend", "Design"],
    reward: 3000,
    currency: "USDC",
    claimingModel: "multi-winner",
    status: "open",
    createdAt: new Date("2024-01-17"),
    updatedAt: new Date("2024-01-17"),
    creator: "mobile_team",
    difficulty: "intermediate",
    deadline: new Date("2024-02-15"),
  },
  {
    id: "bounty-5",
    title: "Write Integration Tests for DEX",
    description:
      "Develop comprehensive integration test suite for decentralized exchange smart contracts.",
    tags: ["Testing", "Smart Contracts", "Backend"],
    reward: 2500,
    currency: "USDC",
    claimingModel: "single-claim",
    status: "open",
    createdAt: new Date("2024-01-16"),
    updatedAt: new Date("2024-01-20"),
    creator: "dex_protocol",
    difficulty: "intermediate",
    deadline: new Date("2024-02-25"),
  },
  {
    id: "bounty-6",
    title: "Optimize Gas Fees for NFT Minting",
    description:
      "Reduce transaction costs for NFT minting operations by optimizing smart contract code.",
    tags: ["Smart Contracts", "NFT", "Backend"],
    reward: 4000,
    currency: "USDC",
    claimingModel: "single-claim",
    status: "completed",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-15"),
    creator: "nft_marketplace",
    difficulty: "advanced",
  },
  {
    id: "bounty-7",
    title: "Create Tutorial Videos for Beginners",
    description:
      "Produce 5 tutorial videos explaining Stellar development basics for newcomers.",
    tags: ["Documentation", "Design"],
    reward: 1500,
    currency: "USDC",
    claimingModel: "multi-winner",
    status: "open",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-18"),
    creator: "education_dao",
    difficulty: "beginner",
    deadline: new Date("2024-03-01"),
  },
  {
    id: "bounty-8",
    title: "Implement Real-Time Price Oracle",
    description:
      "Build reliable price oracle service for DeFi protocols with multiple data sources.",
    tags: ["Backend", "DeFi", "Infrastructure", "Smart Contracts"],
    reward: 6000,
    currency: "USDC",
    claimingModel: "application",
    status: "open",
    createdAt: new Date("2024-01-14"),
    updatedAt: new Date("2024-01-21"),
    creator: "oracle_network",
    difficulty: "advanced",
    deadline: new Date("2024-02-28"),
  },
  {
    id: "bounty-9",
    title: "Add Dark Mode to Dashboard",
    description:
      "Implement dark mode theme with smooth transitions for analytics dashboard.",
    tags: ["Frontend", "Design"],
    reward: 1000,
    currency: "USDC",
    claimingModel: "single-claim",
    status: "in-progress",
    createdAt: new Date("2024-01-13"),
    updatedAt: new Date("2024-01-19"),
    creator: "analytics_platform",
    difficulty: "beginner",
    deadline: new Date("2024-02-08"),
  },
  {
    id: "bounty-10",
    title: "Audit Staking Contract",
    description:
      "Perform comprehensive security audit of staking smart contract with detailed report.",
    tags: ["Security", "Smart Contracts", "Testing"],
    reward: 7000,
    currency: "USDC",
    claimingModel: "single-claim",
    status: "open",
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-22"),
    creator: "staking_protocol",
    difficulty: "advanced",
    deadline: new Date("2024-02-12"),
  },
  {
    id: "bounty-11",
    title: "Build API Documentation Site",
    description:
      "Create interactive API documentation website with code examples and playground.",
    tags: ["Documentation", "Frontend", "Backend"],
    reward: 2800,
    currency: "USDC",
    claimingModel: "competition",
    status: "open",
    createdAt: new Date("2024-01-11"),
    updatedAt: new Date("2024-01-16"),
    creator: "api_team",
    difficulty: "intermediate",
    deadline: new Date("2024-02-18"),
  },
  {
    id: "bounty-12",
    title: "Integrate Wallet Connect",
    description:
      "Add Wallet Connect support to DApp for seamless mobile wallet integration.",
    tags: ["Frontend", "Web3", "Mobile"],
    reward: 3500,
    currency: "USDC",
    claimingModel: "single-claim",
    status: "open",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-20"),
    creator: "dapp_builders",
    difficulty: "intermediate",
    deadline: new Date("2024-02-22"),
  },
];
